"""Markdown report for an authentication analysis run."""

from __future__ import annotations

from collections import Counter
from collections.abc import Sequence

from .models import EnrichedEvent, Finding, Outcome, Severity
from .timeline import build_timeline


def render_markdown(
    events: Sequence[EnrichedEvent],
    findings: Sequence[Finding],
    inputs: Sequence[str],
    title: str = "Authentication analysis",
) -> str:
    """The output has no generation time, so the same input always gives the same report."""
    out = [f"# {title}", ""]
    out += [
        "> Moretti Group lab (FICTITIOUS company). Generated by `moretti-sec`; review every "
        "finding before acting on it.",
        "",
        "## Summary",
        "",
        "| Item | Value |",
        "|---|---|",
        f"| Inputs | {', '.join(f'`{i}`' for i in inputs) or '-'} |",
        f"| Events | {len(events)} |",
    ]
    outcomes = Counter(e.event.outcome for e in events)
    out.append(
        f"| Successful / failed logons | {outcomes[Outcome.SUCCESS]} / "
        f"{outcomes[Outcome.FAILURE]} |"
    )
    if events:
        first = min(e.event.timestamp for e in events)
        last = max(e.event.timestamp for e in events)
        out.append(f"| Period | {first.isoformat()} → {last.isoformat()} |")
    by_severity = Counter(f.severity for f in findings)
    counts = ", ".join(f"{by_severity[s]} {s.value}" for s in reversed(Severity) if by_severity[s])
    out += [f"| Findings | {len(findings)}{f' ({counts})' if counts else ''} |", ""]

    out += ["## Findings", ""]
    if not findings:
        out += ["No findings.", ""]
    for n, f in enumerate(findings, 1):
        out += [
            f"### {n}. [{f.severity.value.upper()}] {f.rule_id} — {f.title}",
            "",
            f.description,
            "",
            f"- **First seen:** {f.first_seen.isoformat() if f.first_seen else '-'}",
            f"- **Events:** {len(f.events)}",
            f"- **MITRE ATT&CK:** {f.mitre or '-'}",
            "",
        ]

    flagged = build_timeline(events, findings, only_flagged=True)
    out += ["## Timeline of flagged events", ""]
    if not flagged:
        out += ["No flagged events.", ""]
    else:
        out += [
            "| Time (UTC) | Host | User | Source | Result | Rules |",
            "|---|---|---|---|---|---|",
        ]
        for entry in flagged:
            e = entry.event
            source = e.event.src_ip or "-"
            if e.src and (e.src.asset_id or e.src.segment):
                source += f" ({e.src.asset_id or e.src.segment})"
            out.append(
                f"| {entry.timestamp.strftime('%Y-%m-%d %H:%M:%S')} | {e.event.host} | "
                f"{e.event.user or '-'} | {source} | {e.event.outcome.value} | "
                f"{', '.join(entry.rule_ids)} |"
            )
        out.append("")

    out += [
        "## Limitations",
        "",
        "- Only the log sources listed above were analyzed; absence of a finding is not "
        "evidence that nothing happened.",
        "- Company context comes from `data/` as it is now; historical changes (for example "
        "a status change after the event) are not reflected.",
        "",
    ]
    return "\n".join(out)


def render_timeline_markdown(items, inputs, title="Correlated timeline"):
    """Markdown for a correlated timeline (moretti_sec.correlate). Deterministic: no run time."""
    from collections import Counter

    out = [
        f"# {title}",
        "",
        "> Moretti Group lab (FICTITIOUS company). Generated by `moretti-sec correlate`; review "
        "every row against the primary evidence.",
        "",
        "## Summary",
        "",
        "| Item | Value |",
        "|---|---|",
        f"| Inputs | {', '.join(f'`{i}`' for i in inputs) or '-'} |",
        f"| Timeline items | {len(items)} |",
    ]
    by_source = Counter(item.source for item in items)
    out.append(
        "| By source | "
        + (", ".join(f"{n} {s}" for s, n in sorted(by_source.items())) or "-")
        + " |"
    )
    if items:
        out.append(
            f"| Period | {items[0].timestamp.isoformat()} → {items[-1].timestamp.isoformat()} |"
        )
    out += ["", "## Timeline", ""]
    if not items:
        out += ["No events.", ""]
        return "\n".join(out)
    out += ["| Time (UTC) | Source | Event | Verdict/Rule |", "|---|---|---|---|"]
    for item in items:
        marker = ", ".join(item.rule_ids) or (item.outcome or "-")
        summary = item.summary.replace("|", "\\|")
        out.append(
            f"| {item.timestamp.strftime('%Y-%m-%d %H:%M:%S')} | {item.source} | "
            f"{summary} | {marker} |"
        )
    out += [
        "",
        "## Limitations",
        "",
        "- Timeline built only from the inputs above; a gap is not evidence that nothing happened.",
        "- Flow Logs aggregate per minute and the Wazuh AWS module polls S3, so network rows can "
        "lag the packets by minutes.",
        "- Company context comes from `data/` as it is now.",
        "",
    ]
    return "\n".join(out)
